name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./vue
    defaults:
      run:
        working-directory: vue
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
    
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install project dependecies
      run: |
        cd vue
        npm ci
      working-directory: ${{ env.working-directory }}

    - name: Run build
      run: |
        cd vue
        npm run build --if-present
        working-directory: ${{ env.working-directory }}
    
    - name: Run tests cases
      run: |
        cd vue
        npm run unit:test --if-present
      working-directory: ${{ env.working-directory }}
